
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-example
  namespace: testing-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: app.192.168.254.141.nip.io
    http:
      paths:
      - path: /one
        pathType: Prefix
        backend:
          service:
            name: test-first
            port:
              number: 8080
      - path: /two
        pathType: Prefix
        backend:
          service:
            name: test-second
            port:
              number: 8080
