
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: testing-namespace
spec:
  ingressClassName: nginx
  rules:
  - host: app1.192.168.254.141.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-first
            port:
              number: 8080
  - host: app2.192.168.254.141.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-second
            port:
              number: 8080

